# Generated by Django 3.2.6 on 2022-02-16 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('urlJson', models.CharField(max_length=300, null=True)),
                ('tipoCampeonato', models.CharField(choices=[('ESTADUAL', 'ESTADUAL'), ('NACIONAL', 'NACIONAL'), ('INTERNACIONAL', 'INTERNACIONAL'), ('REGIONAL', 'REGIONAL')], max_length=20)),
                ('dataInicio', models.DateTimeField()),
                ('dataFim', models.DateTimeField()),
                ('localizacao', models.CharField(max_length=50, null=True)),
                ('numeroRodadaAtual', models.IntegerField(null=True)),
                ('apagado', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3)),
                ('peso', models.FloatField(null=True)),
                ('campeonatoSlug', models.CharField(max_length=50, null=True)),
                ('edicaoSlug', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificacaoClube',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=50, null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.cidade')),
                ('classificacaoClube', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.classificacaoclube')),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('peso', models.FloatField(null=True)),
                ('dataInicio', models.DateTimeField()),
                ('dataFim', models.DateTimeField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.campeonato')),
            ],
        ),
        migrations.RemoveField(
            model_name='evento',
            name='description',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='endYear',
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horarioAlterado',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3),
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('rodada', models.IntegerField(null=True)),
                ('estado', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=3)),
                ('classificacaoJogo', models.CharField(max_length=100)),
                ('idSde', models.IntegerField(null=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.fase')),
                ('mandante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandante', to='gestao.clube')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitante', to='gestao.clube')),
            ],
        ),
    ]
